version: '3.9' # Versión del servicio de .yml, no de Docker.

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: